# Compose file to simplify the build process of the Docker image for this service.
version: "2.1"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "${PWD}/prometheus:/build"
    ports:
      - "3001:9090"
    command:
      - '--config.file=/build/prometheus.yml'

  grafine:
    image: grafana/grafana
    volumes:
      - "${PWD}/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
    ports:
      - "3000:3000"