# Compose file to simplify the build process of the Docker image for this service.
version: "2.1"

services:
  prometheus-monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ACTION=build
      - LOCAL_USER_ID
      - LOCAL_GROUP_ID
    volumes:
      - "$HOME/.m2:/home/go/.m2"
      - "${PWD}:/build"
    ports:
      - "8100:8100"
      - "8101:8101"

  prometheus:
    image: prom/prometheus
    volumes:
      - "${PWD}/buildscripts/prometheus:/cenas"
    ports:
      - "3001:9090"
    command:
      - '--config.file=/cenas/prometheus.yml'

  grafine:
    image: grafana/grafana
    ports:
      - "3000:3000"