scrape_configs:
  - job_name: 'prometheus-spring'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    metrics_path: '/prometheus'

    static_configs:
      - targets: ['prometheus-monitoring:8101']
        labels:
          group: 'test'
